"""Build the UI: split the projection bundle into a PUBLIC inlined payload and a PREMIUM payload
served by a password-gated Vercel serverless function.

Public (inlined into projections.html, visible to anyone): the projection bars + ranges, off/def
and RAPM-arm readouts, market comparison, the Track-record and Drift views, and the glossary --
everything except each team's expanded roster/detail panel.

Premium (returned by ui/api/premium.js only when the shared password matches PREMIUM_PASSWORD):
each team's `players` array and the what-if `grid`. These drive the expanded panel -- rosters,
per-player Off/Def and ~Wins, RAPM disagreement flags, the disagreement-attribution + conviction
block, the offseason-move (trade-undo) chips, and the live what-if editor. The premium data is
embedded in the serverless function (a private-repo file deployed as a function, never served as a
static asset), so it is not readable without the password -- unlike inlining, which view-source
exposes.

    python ui/build.py     # after regenerating snapshots.json
"""
from __future__ import annotations
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
data = json.loads((root / "data/processed/snapshots.json").read_text())

# --- split each season snapshot into public (no players/grid) and premium (players + grid) ---
public = {"meta": data["meta"], "snapshots": {},
          "projection_history": data.get("projection_history", [])}
premium = {}
for key, snap in data["snapshots"].items():
    pub = {k: v for k, v in snap.items() if k not in ("teams", "grid")}
    pub["teams"] = [{k: v for k, v in t.items() if k != "players"} for t in snap["teams"]]
    public["snapshots"][key] = pub
    premium[key] = {
        "teams": {str(t["id"]): t.get("players", []) for t in snap["teams"]},
        "grid": snap.get("grid", {}),
    }

# --- inline the PUBLIC payload into projections.html ---
tpl = (root / "ui/template.html").read_text()
assert "__DATA__" in tpl, "template placeholder missing"
out = root / "ui/projections.html"
out.write_text(tpl.replace("__DATA__", json.dumps(public, separators=(",", ":"))))

# --- generate the password-gated serverless function embedding the PREMIUM payload ---
api_dir = root / "ui/api"
api_dir.mkdir(exist_ok=True)
fn = api_dir / "premium.js"
fn.write_text(
    "// GENERATED by ui/build.py -- do not edit by hand.\n"
    "// Vercel serverless function: returns the premium projection payload (rosters + what-if\n"
    "// grids) ONLY when the request's password matches the PREMIUM_PASSWORD env var. The payload\n"
    "// is embedded here (a function, not a static asset), so it is never publicly readable.\n"
    "const PREMIUM = " + json.dumps(premium, separators=(",", ":")) + ";\n"
    "module.exports = (req, res) => {\n"
    "  const expected = process.env.PREMIUM_PASSWORD;\n"
    "  if (!expected) { res.status(500).json({ error: 'gate not configured' }); return; }\n"
    "  const given = (req.headers['x-unlock-password'] || '').toString();\n"
    "  if (given !== expected) { res.status(401).json({ error: 'wrong password' }); return; }\n"
    "  res.setHeader('Cache-Control', 'private, no-store');\n"
    "  res.status(200).json(PREMIUM);\n"
    "};\n"
)

print(f"wrote {out}  ({out.stat().st_size:,} bytes public, {len(public['snapshots'])} seasons)")
print(f"wrote {fn}  ({fn.stat().st_size:,} bytes premium, gated by PREMIUM_PASSWORD)")
